from __future__ import annotations

import hashlib
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

SETUP_GENERATED_MARKER = "Generated by app-wabbit-dev setup. Do not edit by hand."
SETUP_MANAGED_INTEGRITY_LABEL = "managed-integrity-v1:"
_BASE58_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
_BASE58_RE = re.compile(r"^[1-9A-HJ-NP-Za-km-z]+$")

_REPAIR_GUIDANCE_BY_FILENAME: Mapping[str, str] = {
    "build.gradle.kts": (
        "Update root.clj and rerun dev setup; use build.extra.gradle.kts for durable manual Gradle logic."
    ),
    "settings.gradle.kts": (
        "Update root.clj and rerun dev setup; use settings.local.gradle.kts for local includeBuild and dependency-substitution overrides."
    ),
    "settings.local.gradle.kts": (
        "Update root.clj and rerun dev setup --local instead of editing this generated local overlay directly."
    ),
    "gradle.properties": "Update root.clj and rerun dev setup for durable Gradle property changes.",
    "pyproject.toml": (
        "Update root.clj and rerun dev setup; use pyproject.extra.toml for unmanaged extra TOML sections."
    ),
    "mkdocs.yml": (
        "Update root.clj and rerun dev setup; use mkdocs.extra.yml for unmanaged extra MkDocs top-level keys."
    ),
    "requirements.txt": "Update root.clj and rerun dev setup for durable dependency changes.",
    "requirements-dev.txt": "Update root.clj and rerun dev setup for durable dependency changes.",
}


@dataclass(frozen=True)
class ManagedIntegrityVerification:
    is_managed: bool
    integrity_token: str | None = None
    expected_token: str | None = None
    reason: str | None = None

    @property
    def has_integrity(self) -> bool:
        return self.integrity_token is not None

    @property
    def is_valid(self) -> bool:
        return self.is_managed and self.has_integrity and self.integrity_token == self.expected_token


def render_generated_comment(comment_prefix: str, body_lines: Sequence[str]) -> str:
    prefix = comment_prefix.rstrip()
    lines = [f"{prefix} {SETUP_GENERATED_MARKER}", prefix]
    for line in body_lines:
        if line:
            lines.append(f"{prefix} {line}")
        else:
            lines.append(prefix)
    return "\n".join(lines).rstrip("\n") + "\n"


def prepend_generated_comment(text: str, *, comment_prefix: str, body_lines: Sequence[str]) -> str:
    banner = render_generated_comment(comment_prefix, body_lines)
    stripped = text.lstrip("\n")
    if not stripped:
        return stamp_managed_text(banner, comment_prefix=comment_prefix)
    return stamp_managed_text(banner + "\n" + stripped, comment_prefix=comment_prefix)


def is_setup_managed_text(text: str) -> bool:
    if not text:
        return False
    first_line = text.splitlines()[0]
    return SETUP_GENERATED_MARKER in first_line


def is_setup_managed_file(path: Path) -> bool:
    if not path.is_file():
        return False
    return is_setup_managed_text(path.read_text(encoding="utf-8"))


def managed_file_repair_guidance(path: Path) -> str:
    return _REPAIR_GUIDANCE_BY_FILENAME.get(
        path.name,
        "Update root.clj or the sanctioned override file, then rerun dev setup.",
    )


def _base58_encode(data: bytes) -> str:
    if not data:
        return _BASE58_ALPHABET[0]

    zero_prefix = len(data) - len(data.lstrip(b"\x00"))
    number = int.from_bytes(data, "big")
    encoded: list[str] = []
    while number > 0:
        number, remainder = divmod(number, 58)
        encoded.append(_BASE58_ALPHABET[remainder])
    if not encoded:
        encoded.append(_BASE58_ALPHABET[0])
    encoded.reverse()
    return (_BASE58_ALPHABET[0] * zero_prefix) + "".join(encoded)


def _comment_prefix_for_managed_text(text: str) -> str | None:
    if not is_setup_managed_text(text):
        return None
    first_line = text.splitlines()[0]
    prefix, _, _ = first_line.partition(SETUP_GENERATED_MARKER)
    return prefix.rstrip()


def _integrity_token_from_line(line: str) -> str | None:
    stripped = line.strip()
    if SETUP_MANAGED_INTEGRITY_LABEL not in stripped:
        return None
    _, _, token = stripped.partition(SETUP_MANAGED_INTEGRITY_LABEL)
    token = token.strip()
    if not token:
        return None
    return token


def strip_managed_integrity_lines(text: str) -> str:
    if not text:
        return text
    trailing_newline = text.endswith("\n")
    lines = [line for line in text.splitlines() if _integrity_token_from_line(line) is None]
    stripped = "\n".join(lines)
    if trailing_newline:
        stripped += "\n"
    return stripped


def compute_managed_integrity_token(text: str) -> str:
    canonical = strip_managed_integrity_lines(text)
    digest = hashlib.blake2b(canonical.encode("utf-8"), digest_size=8).digest()
    return _base58_encode(digest)


def stamp_managed_text(text: str, *, comment_prefix: str | None = None) -> str:
    if not is_setup_managed_text(text):
        raise ValueError("Cannot add a managed integrity stamp to text without the generated-file marker")

    canonical = strip_managed_integrity_lines(text)
    effective_prefix = (
        comment_prefix.rstrip() if comment_prefix is not None else _comment_prefix_for_managed_text(canonical)
    )
    if effective_prefix is None:
        raise ValueError("Could not infer comment prefix for managed file")

    lines = canonical.splitlines()
    if not lines:
        raise ValueError("Managed file text must not be empty")

    token = compute_managed_integrity_token(canonical)
    lines.insert(1, f"{effective_prefix} {SETUP_MANAGED_INTEGRITY_LABEL} {token}")
    stamped = "\n".join(lines)
    if canonical.endswith("\n"):
        stamped += "\n"
    return stamped


def verify_managed_text_integrity(text: str) -> ManagedIntegrityVerification:
    if not is_setup_managed_text(text):
        return ManagedIntegrityVerification(is_managed=False)

    integrity_tokens = [token for line in text.splitlines() if (token := _integrity_token_from_line(line)) is not None]
    if not integrity_tokens:
        return ManagedIntegrityVerification(
            is_managed=True,
            reason="missing managed integrity stamp",
        )
    if len(integrity_tokens) > 1:
        return ManagedIntegrityVerification(
            is_managed=True,
            integrity_token=integrity_tokens[0],
            reason="multiple managed integrity stamps found",
        )

    integrity_token = integrity_tokens[0]
    if not _BASE58_RE.fullmatch(integrity_token):
        return ManagedIntegrityVerification(
            is_managed=True,
            integrity_token=integrity_token,
            reason="malformed managed integrity stamp",
        )

    expected_token = compute_managed_integrity_token(text)
    if integrity_token == expected_token:
        return ManagedIntegrityVerification(
            is_managed=True,
            integrity_token=integrity_token,
            expected_token=expected_token,
        )
    return ManagedIntegrityVerification(
        is_managed=True,
        integrity_token=integrity_token,
        expected_token=expected_token,
        reason=f"expected {expected_token} but found {integrity_token}",
    )


def verify_managed_file_integrity(path: Path) -> ManagedIntegrityVerification:
    if not path.is_file():
        return ManagedIntegrityVerification(is_managed=False, reason="not a file")
    return verify_managed_text_integrity(path.read_text(encoding="utf-8"))
