from __future__ import annotations

import hashlib
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

SETUP_GENERATED_MARKER = "Generated by app-wabbit-dev setup. Do not edit by hand."
SETUP_MANAGED_INTEGRITY_LABEL = "managed-integrity-v1:"
_SOLUTION_FILE_HEADER_PREFIX = "Microsoft Visual Studio Solution File, Format Version"
_BASE58_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
_BASE58_RE = re.compile(r"^[1-9A-HJ-NP-Za-km-z]+$")

_REPAIR_GUIDANCE_BY_FILENAME: Mapping[str, str] = {
    ".editorconfig": "Update root.clj and rerun dev setup for durable editor policy changes.",
    "build.gradle.kts": (
        "Update root.clj and rerun dev setup; use build.extra.gradle.kts for durable manual Gradle logic."
    ),
    "settings.gradle.kts": (
        "Update root.clj and rerun dev setup; use settings.local.gradle.kts for local includeBuild and dependency-substitution overrides."
    ),
    "settings.local.gradle.kts": (
        "Update root.clj and rerun dev setup --local instead of editing this generated local overlay directly."
    ),
    "gradle.properties": "Update root.clj and rerun dev setup for durable Gradle property changes.",
    "pyproject.toml": (
        "Update root.clj and rerun dev setup; use pyproject.extra.toml for unmanaged extra TOML sections."
    ),
    "mkdocs.yml": (
        "Update root.clj and rerun dev setup; use mkdocs.extra.yml for unmanaged extra MkDocs top-level keys."
    ),
    "CODEOWNERS": "Update root.clj code-owner entries and rerun dev setup.",
    "SECURITY.md": "Update root.clj or the generated repository metadata templates, then rerun dev setup.",
    "pull_request_template.md": "Update root.clj or the generated repository metadata templates, then rerun dev setup.",
    "bug_report.yml": "Update root.clj or the generated repository metadata templates, then rerun dev setup.",
    "feature_request.yml": "Update root.clj or the generated repository metadata templates, then rerun dev setup.",
    "requirements.txt": "Update root.clj and rerun dev setup for durable dependency changes.",
    "requirements-dev.txt": "Update root.clj and rerun dev setup for durable dependency changes.",
}


@dataclass(frozen=True)
class ManagedIntegrityVerification:
    is_managed: bool
    integrity_token: str | None = None
    expected_token: str | None = None
    reason: str | None = None

    @property
    def has_integrity(self) -> bool:
        return self.integrity_token is not None

    @property
    def is_valid(self) -> bool:
        return self.is_managed and self.has_integrity and self.integrity_token == self.expected_token


@dataclass(frozen=True)
class CommentStyle:
    prefix: str
    suffix: str | None = None


def _render_comment_line(style: CommentStyle, text: str = "") -> str:
    prefix = style.prefix.rstrip()
    suffix = style.suffix.strip() if style.suffix is not None else ""
    if text:
        line = f"{prefix} {text}"
    else:
        line = prefix
    if suffix:
        line = f"{line} {suffix}"
    return line


def render_generated_comment(
    comment_prefix: str,
    body_lines: Sequence[str],
    *,
    comment_suffix: str | None = None,
) -> str:
    style = CommentStyle(prefix=comment_prefix, suffix=comment_suffix)
    lines = [_render_comment_line(style, SETUP_GENERATED_MARKER), _render_comment_line(style)]
    for line in body_lines:
        if line:
            lines.append(_render_comment_line(style, line))
        else:
            lines.append(_render_comment_line(style))
    return "\n".join(lines).rstrip("\n") + "\n"


def prepend_generated_comment(
    text: str,
    *,
    comment_prefix: str,
    body_lines: Sequence[str],
    comment_suffix: str | None = None,
) -> str:
    banner = render_generated_comment(comment_prefix, body_lines, comment_suffix=comment_suffix)
    stripped = text.lstrip("\n")
    if not stripped:
        return stamp_managed_text(banner, comment_prefix=comment_prefix, comment_suffix=comment_suffix)
    if stripped.startswith("<?xml"):
        declaration, separator, remainder = stripped.partition("\n")
        if separator:
            managed_body = declaration + "\n" + banner + "\n" + remainder
        else:
            managed_body = declaration + "\n" + banner
        return stamp_managed_text(
            managed_body,
            comment_prefix=comment_prefix,
            comment_suffix=comment_suffix,
        )
    if _starts_with_solution_header(stripped):
        header, separator, remainder = stripped.partition("\n")
        if separator:
            managed_body = header + "\n" + banner + "\n" + remainder
        else:
            managed_body = header + "\n" + banner
        return stamp_managed_text(
            managed_body,
            comment_prefix=comment_prefix,
            comment_suffix=comment_suffix,
        )
    return stamp_managed_text(
        banner + "\n" + stripped,
        comment_prefix=comment_prefix,
        comment_suffix=comment_suffix,
    )


def is_setup_managed_text(text: str) -> bool:
    if not text:
        return False
    lines = text.splitlines()
    if not lines:
        return False
    first_line = lines[0]
    if SETUP_GENERATED_MARKER in first_line:
        return True
    if first_line.lstrip().startswith("<?xml") and len(lines) > 1:
        return SETUP_GENERATED_MARKER in lines[1]
    if _starts_with_solution_header(text) and len(lines) > 1:
        return SETUP_GENERATED_MARKER in lines[1]
    return False


def is_setup_managed_file(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        return is_setup_managed_text(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError):
        return False


def managed_file_repair_guidance(path: Path) -> str:
    return _REPAIR_GUIDANCE_BY_FILENAME.get(
        path.name,
        "Update root.clj or the sanctioned override file, then rerun dev setup.",
    )


def _base58_encode(data: bytes) -> str:
    if not data:
        return _BASE58_ALPHABET[0]

    zero_prefix = len(data) - len(data.lstrip(b"\x00"))
    number = int.from_bytes(data, "big")
    encoded: list[str] = []
    while number > 0:
        number, remainder = divmod(number, 58)
        encoded.append(_BASE58_ALPHABET[remainder])
    if not encoded:
        encoded.append(_BASE58_ALPHABET[0])
    encoded.reverse()
    return (_BASE58_ALPHABET[0] * zero_prefix) + "".join(encoded)


def _comment_style_for_managed_text(text: str) -> CommentStyle | None:
    if not is_setup_managed_text(text):
        return None
    lines = text.splitlines()
    if not lines:
        return None
    marker_line = lines[0]
    if marker_line.lstrip().startswith("<?xml") and len(lines) > 1:
        marker_line = lines[1]
    elif _starts_with_solution_header(text) and len(lines) > 1:
        marker_line = lines[1]
    prefix, _, suffix = marker_line.partition(SETUP_GENERATED_MARKER)
    normalized_prefix = prefix.rstrip()
    normalized_suffix = suffix.strip() or None
    return CommentStyle(prefix=normalized_prefix, suffix=normalized_suffix)


def _integrity_token_from_line(line: str) -> str | None:
    stripped = line.strip()
    if SETUP_MANAGED_INTEGRITY_LABEL not in stripped:
        return None
    _, _, token = stripped.partition(SETUP_MANAGED_INTEGRITY_LABEL)
    token = token.strip().split()[0] if token.strip() else ""
    if not token:
        return None
    return token


def strip_managed_integrity_lines(text: str) -> str:
    if not text:
        return text
    trailing_newline = text.endswith("\n")
    lines = [line for line in text.splitlines() if _integrity_token_from_line(line) is None]
    stripped = "\n".join(lines)
    if trailing_newline:
        stripped += "\n"
    return stripped


def compute_managed_integrity_token(text: str) -> str:
    canonical = strip_managed_integrity_lines(text)
    digest = hashlib.blake2b(canonical.encode("utf-8"), digest_size=8).digest()
    return _base58_encode(digest)


def stamp_managed_text(
    text: str,
    *,
    comment_prefix: str | None = None,
    comment_suffix: str | None = None,
) -> str:
    if not is_setup_managed_text(text):
        raise ValueError("Cannot add a managed integrity stamp to text without the generated-file marker")

    canonical = strip_managed_integrity_lines(text)
    effective_style = (
        CommentStyle(prefix=comment_prefix, suffix=comment_suffix)
        if comment_prefix is not None
        else _comment_style_for_managed_text(canonical)
    )
    if effective_style is None:
        raise ValueError("Could not infer comment prefix for managed file")

    lines = canonical.splitlines()
    if not lines:
        raise ValueError("Managed file text must not be empty")

    token = compute_managed_integrity_token(canonical)
    insert_index = 1
    if lines[0].lstrip().startswith("<?xml"):
        insert_index = 2
    elif _starts_with_solution_header(canonical):
        insert_index = 2
    lines.insert(insert_index, _render_comment_line(effective_style, f"{SETUP_MANAGED_INTEGRITY_LABEL} {token}"))
    stamped = "\n".join(lines)
    if canonical.endswith("\n"):
        stamped += "\n"
    return stamped


def _starts_with_solution_header(text: str) -> bool:
    first_line, _, _ = text.partition("\n")
    return first_line.startswith(_SOLUTION_FILE_HEADER_PREFIX)


def verify_managed_text_integrity(text: str) -> ManagedIntegrityVerification:
    if not is_setup_managed_text(text):
        return ManagedIntegrityVerification(is_managed=False)

    integrity_tokens = [token for line in text.splitlines() if (token := _integrity_token_from_line(line)) is not None]
    if not integrity_tokens:
        return ManagedIntegrityVerification(
            is_managed=True,
            reason="missing managed integrity stamp",
        )
    if len(integrity_tokens) > 1:
        return ManagedIntegrityVerification(
            is_managed=True,
            integrity_token=integrity_tokens[0],
            reason="multiple managed integrity stamps found",
        )

    integrity_token = integrity_tokens[0]
    if not _BASE58_RE.fullmatch(integrity_token):
        return ManagedIntegrityVerification(
            is_managed=True,
            integrity_token=integrity_token,
            reason="malformed managed integrity stamp",
        )

    expected_token = compute_managed_integrity_token(text)
    if integrity_token == expected_token:
        return ManagedIntegrityVerification(
            is_managed=True,
            integrity_token=integrity_token,
            expected_token=expected_token,
        )
    return ManagedIntegrityVerification(
        is_managed=True,
        integrity_token=integrity_token,
        expected_token=expected_token,
        reason=f"expected {expected_token} but found {integrity_token}",
    )


def verify_managed_file_integrity(path: Path) -> ManagedIntegrityVerification:
    if not path.is_file():
        return ManagedIntegrityVerification(is_managed=False, reason="not a file")
    return verify_managed_text_integrity(path.read_text(encoding="utf-8"))
