from __future__ import annotations

from pathlib import Path

import pytest

from dev.generated_files import (
    SETUP_MANAGED_INTEGRITY_LABEL,
    is_setup_managed_file,
    prepend_generated_comment,
    stamp_managed_text,
    verify_managed_file_integrity,
    verify_managed_text_integrity,
)
from dev.tasks import check as check_task


def test_prepend_generated_comment_adds_valid_integrity_stamp() -> None:
    managed_text = prepend_generated_comment(
        '[tool.poetry]\nname = "demo"\n',
        comment_prefix="#",
        body_lines=["This file is generated from workspace configuration in root.clj."],
    )

    lines = managed_text.splitlines()
    assert lines[0] == "# Generated by app-wabbit-dev setup. Do not edit by hand."
    assert lines[1].startswith(f"# {SETUP_MANAGED_INTEGRITY_LABEL} ")

    verification = verify_managed_text_integrity(managed_text)
    assert verification.is_valid


def test_prepend_generated_comment_supports_html_comment_style() -> None:
    managed_text = prepend_generated_comment(
        "# Security Policy\n",
        comment_prefix="<!--",
        comment_suffix="-->",
        body_lines=["This file is generated from workspace configuration in root.clj."],
    )

    lines = managed_text.splitlines()
    assert lines[0] == "<!-- Generated by app-wabbit-dev setup. Do not edit by hand. -->"
    assert lines[1].startswith(f"<!-- {SETUP_MANAGED_INTEGRITY_LABEL} ")
    assert lines[1].endswith("-->")

    verification = verify_managed_text_integrity(managed_text)
    assert verification.is_valid


def test_prepend_generated_comment_keeps_xml_declaration_first() -> None:
    managed_text = prepend_generated_comment(
        '<?xml version="1.0" encoding="utf-8"?>\n<configuration />\n',
        comment_prefix="<!--",
        comment_suffix="-->",
        body_lines=["This file is generated from workspace configuration in root.clj."],
    )

    lines = managed_text.splitlines()
    assert lines[0] == '<?xml version="1.0" encoding="utf-8"?>'
    assert lines[1] == "<!-- Generated by app-wabbit-dev setup. Do not edit by hand. -->"
    assert lines[2].startswith(f"<!-- {SETUP_MANAGED_INTEGRITY_LABEL} ")

    verification = verify_managed_text_integrity(managed_text)
    assert verification.is_valid


def test_stamp_managed_text_is_idempotent() -> None:
    stamped_once = stamp_managed_text("// Generated by app-wabbit-dev setup. Do not edit by hand.\n//\nplugins {}\n")
    stamped_twice = stamp_managed_text(stamped_once)

    assert stamped_twice == stamped_once


def test_verify_managed_integrity_detects_manual_edit(tmp_path: Path) -> None:
    path = tmp_path / "pyproject.toml"
    managed_text = prepend_generated_comment(
        '[tool.poetry]\nname = "demo"\n',
        comment_prefix="#",
        body_lines=["This file is generated from workspace configuration in root.clj."],
    )
    path.write_text(managed_text, encoding="utf-8")
    path.write_text(path.read_text(encoding="utf-8").replace('name = "demo"', 'name = "changed"'), encoding="utf-8")

    verification = verify_managed_file_integrity(path)

    assert verification.is_managed
    assert verification.has_integrity
    assert not verification.is_valid
    assert verification.reason is not None
    assert "expected" in verification.reason


def test_is_setup_managed_file_returns_false_for_binary_files(tmp_path: Path) -> None:
    path = tmp_path / "icon.png"
    path.write_bytes(b"\x89PNG\r\n\x1a\n\x00\xb8")

    assert is_setup_managed_file(path) is False


def test_check_main_reports_managed_generated_file_edit(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    from dev.checks.managed_generated_files import ManagedGeneratedFileIntegrityCheck

    path = tmp_path / "pyproject.toml"
    managed_text = prepend_generated_comment(
        '[tool.poetry]\nname = "demo"\n',
        comment_prefix="#",
        body_lines=["This file is generated from workspace configuration in root.clj."],
    )
    path.write_text(managed_text.replace('name = "demo"', 'name = "changed"'), encoding="utf-8")

    monkeypatch.setattr(
        check_task.Module,
        "load_modules",
        staticmethod(lambda: {"ManagedGeneratedFileIntegrityCheck": ManagedGeneratedFileIntegrityCheck()}),
    )

    result = check_task.check_main(str(path))

    assert result == 1
    captured = capsys.readouterr()
    output = captured.out + captured.err
    assert "E_MANAGED_GENERATED_FILE_EDITED" in output
    assert "pyproject.extra.toml" in output
