from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import jinja2
from git import Repo
from mu.parser import parse

from dev.checks.repo_properties import RepoMetadataHygieneCheck
from dev.config import CodeOwner, Config, OwnershipType, PythonProject


def _make_python_project(path: Path, *, github_repo: str | None) -> PythonProject:
    return PythonProject(
        path=path,
        name=path.name,
        version=None,
        description="Demo",
        authors=[],
        license="AGPL",
        github_repo=github_repo,
        requires_python=">=3.10",
        dependencies=[],
        dev_dependencies=[],
        scripts=[],
        application=None,
        homepage=None,
        repository=None,
        keywords=[],
        classifiers=[],
        quarantine=False,
        publish=False,
        ownership=OwnershipType.WABBIT,
        resolved_dependencies=[],
    )


def test_write_repo_metadata_files_generates_editorconfig_and_github_bundle(tmp_path: Path) -> None:
    import dev.tasks.setup as setup_module

    repo_root = tmp_path / "demo"
    repo_root.mkdir(parents=True, exist_ok=True)
    project = _make_python_project(repo_root, github_repo="wabbit-corp/demo")
    project.project_id = "demo"

    config = Config(raw=parse("()"))
    config.default_company_email = "security@wabbit.one"
    config.default_code_owners = [CodeOwner(name="Sir Wabbit", email="wabbit@wabbit.one")]
    config.defined_projects["demo"] = project

    ctx = SimpleNamespace(
        config=config,
        editorconfig_template=jinja2.Template("root = true\n\n[*.py]\nmax_line_length = {{ line_length }}\n"),
        github_codeowners_template=jinja2.Template(
            "{% for owner in code_owners -%}\n# {{ owner.name }} <{{ owner.email }}>\n{% endfor -%}\n* {% for owner in code_owners %}{{ owner.email }}{% endfor %}\n"
        ),
        github_security_template=jinja2.Template("# Security Policy\n\nEmail {{ contact_email }}\n"),
        github_pull_request_template=jinja2.Template("## Summary\n"),
        github_issue_bug_template=jinja2.Template("name: Bug report\n"),
        github_issue_feature_template=jinja2.Template("name: Feature request\n"),
    )

    written_roots = setup_module._write_repo_metadata_files(ctx, [project])

    assert written_roots == [str(repo_root.resolve())]
    assert (repo_root / ".editorconfig").is_file()
    assert (repo_root / ".github" / "CODEOWNERS").is_file()
    assert (repo_root / ".github" / "SECURITY.md").is_file()
    assert (repo_root / ".github" / "pull_request_template.md").is_file()
    assert (repo_root / ".github" / "ISSUE_TEMPLATE" / "bug_report.yml").is_file()
    assert (repo_root / ".github" / "ISSUE_TEMPLATE" / "feature_request.yml").is_file()

    codeowners_text = (repo_root / ".github" / "CODEOWNERS").read_text(encoding="utf-8")
    assert "wabbit@wabbit.one" in codeowners_text
    assert "Generated by app-wabbit-dev setup" in codeowners_text

    security_text = (repo_root / ".github" / "SECURITY.md").read_text(encoding="utf-8")
    assert "<!-- Generated by app-wabbit-dev setup. Do not edit by hand. -->" in security_text
    assert "security@wabbit.one" in security_text


def test_repo_metadata_hygiene_check_reports_missing_repo_files(tmp_path: Path) -> None:
    workspace_root = tmp_path
    repo_root = workspace_root / "demo"
    repo_root.mkdir(parents=True, exist_ok=True)
    Repo.init(repo_root).close()

    (workspace_root / "root.clj").write_text(
        "\n".join(
            [
                '(default-company-email "security@wabbit.one")',
                '(code-owner "Sir Wabbit" "wabbit@wabbit.one")',
                '(python "demo" "0.1.0" :repo "wabbit-corp/demo")',
                "",
            ]
        ),
        encoding="utf-8",
    )
    (workspace_root / "root.private.clj").write_text('(github-token "dummy")\n', encoding="utf-8")

    issues = RepoMetadataHygieneCheck().check(repo_root, None)
    issue_ids = {issue.issue_type.id for issue in issues}

    assert "E_MISSING_EDITORCONFIG" in issue_ids
    assert "E_MISSING_CODEOWNERS" in issue_ids
    assert "E_MISSING_SECURITY_POLICY" in issue_ids
    assert "E_MISSING_PULL_REQUEST_TEMPLATE" in issue_ids
    assert "E_MISSING_ISSUE_TEMPLATE" in issue_ids
    assert "E_MISSING_REPO_WORKFLOW" in issue_ids


def test_repo_metadata_hygiene_check_warns_when_codeowners_are_unconfigured(tmp_path: Path) -> None:
    workspace_root = tmp_path
    repo_root = workspace_root / "demo"
    repo_root.mkdir(parents=True, exist_ok=True)
    Repo.init(repo_root).close()

    (workspace_root / "root.clj").write_text(
        "\n".join(
            [
                '(default-company-email "security@wabbit.one")',
                '(python "demo" "0.1.0" :repo "wabbit-corp/demo")',
                "",
            ]
        ),
        encoding="utf-8",
    )
    (workspace_root / "root.private.clj").write_text('(github-token "dummy")\n', encoding="utf-8")

    issues = RepoMetadataHygieneCheck().check(repo_root, None)

    assert any(issue.issue_type.id == "E_REPO_CODEOWNERS_UNCONFIGURED" for issue in issues)
