from __future__ import annotations

from pathlib import Path

import pytest

from dev.template_assets import repo_template_path


def _gradle_template_path(template_name: str) -> Path:
    return repo_template_path("gradle-files", template_name)


@pytest.mark.parametrize(
    "template_name",
    [
        "build.gradle.kts.jinja2",
        "settings.gradle.kts.jinja2",
        "settings.local.gradle.kts.jinja2",
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
        "subproject-settings.gradle.kts.jinja2",
    ],
)
def test_gradle_templates_mark_generated_files(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert content.startswith("// Generated by app-wabbit-dev setup. Do not edit by hand.\n")


@pytest.mark.parametrize(
    "template_name",
    [
        "build.gradle.kts.jinja2",
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_build_templates_explain_how_to_regenerate(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "This file is generated from workspace configuration in root.clj." in content
    assert "dev setup <project-or-repo>" in content
    assert "build.extra.gradle.kts" in content
    assert "Direct edits to this file will be overwritten" in content


@pytest.mark.parametrize(
    "template_name",
    [
        "settings.gradle.kts.jinja2",
        "subproject-settings.gradle.kts.jinja2",
    ],
)
def test_gradle_settings_templates_explain_local_override_file(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "This file is generated from workspace configuration in root.clj." in content
    assert "dev setup <project-or-repo>" in content
    assert "settings.local.gradle.kts" in content
    assert "Direct edits to this file will be overwritten" in content


def test_gradle_local_settings_template_explains_local_regeneration_mode() -> None:
    template_path = _gradle_template_path("settings.local.gradle.kts.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert "LOCAL setup mode" in content
    assert "dev setup --local <project-or-repo>" in content
    assert "generated local overlay" in content


def test_gradle_properties_template_marks_file_as_generated() -> None:
    template_path = _gradle_template_path("gradle.properties.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert content.startswith("# Generated by app-wabbit-dev setup. Do not edit by hand.\n")
    assert "This file is generated from workspace configuration in root.clj." in content
    assert "dev setup <project-or-repo>" in content


def test_gradle_pages_markdown_site_helper_script_exists() -> None:
    script_path = repo_template_path("gradle-files", "scripts", "build_pages_markdown_site.py")

    content = script_path.read_text(encoding="utf-8")

    assert script_path.is_file()
    assert content.startswith("#!/usr/bin/env python3\n")


def test_settings_templates_place_plugin_builds_under_plugin_management() -> None:
    settings_template_path = _gradle_template_path("settings.gradle.kts.jinja2")
    subproject_settings_template_path = _gradle_template_path("subproject-settings.gradle.kts.jinja2")
    settings_local_template_path = _gradle_template_path("settings.local.gradle.kts.jinja2")

    settings_content = settings_template_path.read_text(encoding="utf-8")
    subproject_settings_content = subproject_settings_template_path.read_text(encoding="utf-8")
    settings_local_content = settings_local_template_path.read_text(encoding="utf-8")

    assert "pluginManagement {" in settings_content
    assert "pluginManagement {" in subproject_settings_content
    assert settings_content.count("mavenCentral()") >= 2
    assert subproject_settings_content.count("mavenCentral()") >= 2
    assert 'includeBuild("{{ plugin_build.build_path }}")' in settings_content
    assert 'includeBuild("{{ plugin_build.build_path }}")' in subproject_settings_content
    assert "dependencySubstitution" in settings_local_content


@pytest.mark.parametrize(
    "template_name",
    [
        "settings.gradle.kts.jinja2",
        "subproject-settings.gradle.kts.jinja2",
    ],
)
def test_gradle_settings_templates_support_local_overlay_and_maven_local_flags(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "wabbit.useLocalBuildOverrides" in content
    assert "WABBIT_USE_LOCAL_BUILD_OVERRIDES" in content
    assert "wabbit.applyLocalSettingsOverlay" in content
    assert "WABBIT_APPLY_LOCAL_SETTINGS_OVERLAY" in content
    assert "if (useLocalBuildOverrides && localSettingsFile.isFile)" in content
    assert "wabbit.useMavenLocalArtifacts" in content
    assert "WABBIT_USE_MAVEN_LOCAL_ARTIFACTS" in content
    assert "useLocalBuildOverridesInPluginManagement" in content
    assert 'includeGroupByRegex("one\\\\.wabbit\\\\..+")' in content
    assert content.count("mavenLocal {") >= 2


@pytest.mark.parametrize(
    "template_name",
    [
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_build_templates_support_local_maven_artifact_flag(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "wabbit.useMavenLocalArtifacts" in content
    assert "WABBIT_USE_MAVEN_LOCAL_ARTIFACTS" in content
    assert 'includeGroupByRegex("one\\\\.wabbit\\\\..+")' in content
    assert "mavenLocal {" in content


def test_scala_template_uses_scala3_scalatest_coordinates() -> None:
    template_path = _gradle_template_path("subproject-build.gradle.kts.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert "org.scalatest:scalatest_3:3.2.19" in content
    assert "org.scalatestplus:junit-5-10_3:3.2.19.0" in content


def test_gradle_properties_template_enables_cinterop_commonization() -> None:
    template_path = _gradle_template_path("gradle.properties.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert "kotlin.mpp.enableCInteropCommonization=true" in content


@pytest.mark.parametrize(
    "template_name",
    [
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_templates_do_not_embed_placeholder_dokka_source_url(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "https://example.com/src" not in content
    assert "dokka_source_link_remote_url" in content
    assert "company_legal_name" in content


@pytest.mark.parametrize(
    "template_name",
    [
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_templates_auto_include_dokka_docs_assets(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert 'file("docs/dokka-module.md")' in content
    assert "dokkaModuleFile.exists()" in content
    assert "includes.from(dokkaModuleFile)" in content


@pytest.mark.parametrize(
    "template_name",
    [
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_templates_skip_signing_for_maven_local_publish(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "localPublishRequested" in content
    assert '"MavenLocal" in taskName' in content
    assert "tasks.withType<org.gradle.plugins.signing.Sign>().configureEach" in content
    assert "enabled = false" in content


@pytest.mark.parametrize(
    "template_name",
    [
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_templates_enable_context_parameters_by_default(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert 'freeCompilerArgs.add("-Xcontext-parameters")' in content
    assert "-Xcontext-receivers" not in content


@pytest.mark.parametrize(
    "template_name",
    [
        "build.gradle.kts.jinja2",
        "subproject-build.gradle.kts.jinja2",
        "subproject-build-kmp.gradle.kts.jinja2",
    ],
)
def test_gradle_build_templates_apply_optional_extra_file(template_name: str) -> None:
    template_path = _gradle_template_path(template_name)
    content = template_path.read_text(encoding="utf-8")

    assert "inline_extra_build_imports" in content
    assert "inline_extra_build_script" in content
    assert 'file("build.extra.gradle.kts")' in content
    assert "apply(from = extraBuildFile)" in content


def test_gradle_jvm_subproject_template_sets_java_release_and_paper_depend() -> None:
    template_path = _gradle_template_path("subproject-build.gradle.kts.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert "options.release.set({{ java_version }})" in content
    assert "features['paper-plugin'].depend or []" in content


def test_gradle_kmp_template_remaps_publication_artifact_ids() -> None:
    template_path = _gradle_template_path("subproject-build-kmp.gradle.kts.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert 'val configuredArtifactId = "{{ published_artifact_id }}"' in content
    assert "artifactId == project.name -> configuredArtifactId" in content
    assert "artifactId.startsWith(projectArtifactPrefix)" in content


def test_gradle_templates_declare_both_intellij_gradle_plugin_variants() -> None:
    settings_template = _gradle_template_path("settings.gradle.kts.jinja2")
    subproject_settings_template = _gradle_template_path("subproject-settings.gradle.kts.jinja2")

    settings_content = settings_template.read_text(encoding="utf-8")
    subproject_settings_content = subproject_settings_template.read_text(encoding="utf-8")

    assert 'id("org.jetbrains.intellij") version "{{ intellij_gradle_plugin_version }}"' in settings_content
    assert (
        'id("org.jetbrains.intellij.platform") version "{{ intellij_platform_gradle_plugin_version }}"'
        in settings_content
    )
    assert (
        'id("org.jetbrains.intellij.platform.module") version "{{ intellij_platform_gradle_plugin_version }}"'
        in settings_content
    )
    assert 'id("org.jetbrains.intellij") version "{{ intellij_gradle_plugin_version }}"' in subproject_settings_content
    assert (
        'id("org.jetbrains.intellij.platform") version "{{ intellij_platform_gradle_plugin_version }}"'
        in subproject_settings_content
    )
    assert (
        'id("org.jetbrains.intellij.platform.module") version "{{ intellij_platform_gradle_plugin_version }}"'
        in subproject_settings_content
    )


def test_gradle_jvm_subproject_template_supports_intellij_platform_gradle_plugin_v2() -> None:
    template_path = _gradle_template_path("subproject-build.gradle.kts.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert "use_intellij_platform_gradle_plugin_v2" in content
    assert "intellij-platform-library" in content
    assert "uses_intellij_platform_dependencies" in content
    assert 'id("org.jetbrains.intellij.platform{% if features[\'intellij-platform-library\'].modulePlugin %}.module{% endif %}")' in content
    assert "intellijPlatform {" in content
    assert 'intellijIdea("{{ intellij_platform_idea_version }}")' in content
    assert "testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform)" in content
    assert "untilBuild = provider { null }" in content


def test_gradle_jvm_subproject_template_supports_kotlin_gradle_plugin_libraries() -> None:
    template_path = _gradle_template_path("subproject-build.gradle.kts.jinja2")
    content = template_path.read_text(encoding="utf-8")

    assert "is_kotlin_gradle_plugin_library_project" in content
    assert 'compileOnly(gradleApi())' in content
    assert 'compileOnly("org.jetbrains.kotlin:kotlin-gradle-plugin:' in content
