import dataclasses
import io
import json
import os
import sys
from contextlib import nullcontext, redirect_stdout
from dataclasses import dataclass
from pathlib import Path

import jinja2
from git import Repo

import dev.io
from dev.ai import ensure_semver_impact_line, suggest_commit_name
from dev.base import Scope
from dev.build_order import toposort_projects
from dev.config import (
    Config,
    DataProject,
    Dependency,
    GradleProject,
    OwnershipType,
    PremakeProject,
    Project,
    ProjectDependencyTarget,
    PurescriptProject,
    PythonProject,
    get_gradle_plugin_applications,
    load_config,
    project_repo_root,
    resolve_kotlin_plugin_compiler_plugin_project,
    resolve_kotlin_plugin_project,
)
from dev.generated_files import stamp_managed_text
from dev.git_changes import ChangeType, FileDiff, FileType, compute_repo_diffs
from dev.licenses import canonicalize_license_key, load_license_texts
from dev.messages import ask, error, info, warning
from dev.tasks import setup_common, setup_kotlin, setup_python
from dev.tasks.setup_common import RepoSetupMode, render_template

GENERATED_GRADLE_FILE_HEADER = "// Generated by app-wabbit-dev setup. Do not edit by hand."


@dataclass
class RepoInfo:
    organization: str
    name: str
    is_private: bool

    @property
    def full_name(self) -> str:
        return f"{self.organization}/{self.name}"

    @property
    def is_public(self) -> bool:
        return not self.is_private


@dataclass
class RepoSetupContext:
    config: Config
    known_repo_names: list[str]
    known_github_repos: dict[str, RepoInfo]
    is_github_api_available: bool

    repo_template: Path

    licenses: dict[str, str]
    coc: jinja2.Template

    gitignore_template: jinja2.Template
    cla: jinja2.Template
    cla_explanations: jinja2.Template
    contributor_privacy_policy: jinja2.Template

    settings_template: jinja2.Template
    settings_local_template: jinja2.Template
    subproject_settings_template: jinja2.Template
    build_template: jinja2.Template
    subproject_build_template: jinja2.Template
    subproject_build_kmp_template: jinja2.Template
    gradle_gitignore_template: jinja2.Template
    gradle_properties_template: jinja2.Template
    python_gitignore_template: jinja2.Template
    purescript_gitignore_template: jinja2.Template
    python_pyproject_template: jinja2.Template
    python_pyrightconfig_template: jinja2.Template
    python_mkdocs_template: jinja2.Template
    python_docs_index_template: jinja2.Template
    python_docs_installation_template: jinja2.Template
    python_docs_development_template: jinja2.Template
    python_contributing_template: jinja2.Template
    python_docs_quality_workflow_template: jinja2.Template
    python_docs_deploy_workflow_template: jinja2.Template
    gradle_release_publish_workflow_template: jinja2.Template
    gradle_snapshot_publish_workflow_template: jinja2.Template
    gradle_compiler_plugin_release_publish_workflow_template: jinja2.Template
    gradle_compiler_plugin_snapshot_publish_workflow_template: jinja2.Template
    gradle_docs_quality_workflow_template: jinja2.Template
    gradle_docs_deploy_workflow_template: jinja2.Template
    python_codespell_ignore_words_template: jinja2.Template
    python_build_executable_template: jinja2.Template

    mode: RepoSetupMode


@dataclass(frozen=True)
class WorkspaceDependencySubstitution:
    module_coordinate: str
    gradle_project_name: str


@dataclass(frozen=True)
class LocalIncludedBuildSubstitution:
    module_coordinate: str
    project_path: str


@dataclass(frozen=True)
class LocalIncludedBuild:
    build_path: str
    substitutions: list[LocalIncludedBuildSubstitution]


def setup_project(
    ctx: RepoSetupContext,
    project: Project,
    interactive: bool = True,
    commit_changes: bool = True,
    allow_push: bool = True,
) -> None:
    name = project.name
    repo_path = project_repo_root(project)
    repo_managed_gradle_project = isinstance(project, GradleProject) and project.effective_gradle_root != project.path

    # Each project should have a directory before project-type setup writes files.
    if not project.path.exists():
        error(f"Directory for {project.name} does not exist")
        if not interactive or ask(f"Create directory for {project.name}?"):
            project.path.mkdir(parents=True, exist_ok=True)
        else:
            raise Exception("Directory does not exist")

    # Project directory should be a directory (lol).
    if not project.path.is_dir():
        error(f"{project.path} is not a directory")
        return

    with Scope() as scope:
        if not project.managed_by_setup and not repo_managed_gradle_project:
            info(f"Skipping file generation for repo-managed project {project.name}")
        else:
            if isinstance(project, GradleProject):
                setup_gradle_project(ctx, project, interactive=interactive)
            elif isinstance(project, PythonProject):
                setup_python_project(ctx, project, interactive=interactive)
            elif isinstance(project, PurescriptProject):
                setup_purescript_project(ctx, project, interactive=interactive)
            elif isinstance(project, PremakeProject):
                _write_wabbit_legal_files(ctx, project)
            elif isinstance(project, DataProject):
                _write_wabbit_legal_files(ctx, project)
            else:
                error(f"No setup function for project: {name}")

        # git push --set-upstream origin master
        # if repo is not None:
        #     if repo.active_branch.name == 'master':
        #         if repo.active_branch.tracking_branch() is None:
        #             repo.git.push('--set-upstream', 'origin', 'master')

        if project.github_repo is None:
            error(f"Github repository not set for {project.name}")
            return

        is_github_repo_set = True
        if ctx.is_github_api_available:
            # If set and API is available, Github repo should exist.
            if project.github_repo not in ctx.known_repo_names:
                error(f"Remote repository {project.github_repo} does not exist")
                return
        else:
            warning("GitHub API unavailable; skipping remote existence check.")

        # Each project should have a .git directory
        if is_github_repo_set:
            if not (repo_path / ".git").exists():
                error(f"{project.name} does not have .git")
                if not interactive or ask(f"Initialize git repository for {project.name}?"):
                    repo_path.mkdir(parents=True, exist_ok=True)
                    repo = Repo.init(repo_path)
                    scope.defer(repo.close)

                    # Set default user and email
                    repo.config_writer().set_value("user", "email", ctx.config.default_git_user_email).set_value(
                        "user", "name", ctx.config.default_git_user_name
                    ).release()
                else:
                    raise Exception(".git does not exist")

            elif not (repo_path / ".git").is_dir():
                error(f"{project.name} has a non-directory named .git")
                repo = None
            else:
                repo = Repo(repo_path)
                scope.defer(repo.close)
        else:
            repo = None

        # Check that username and email are set
        if repo is not None:
            config = repo.config_reader()
            if config.has_section("user"):
                current_email = config.get_value("user", "email", default=None)
                current_name = config.get_value("user", "name", default=None)
            else:
                current_email = None
                current_name = None
            config.release()

            if current_email != ctx.config.default_git_user_email:
                warning(f"{project.name} has a different git user email: {current_email}")
                repo.config_writer().set_value("user", "email", ctx.config.default_git_user_email).release()
            if current_name != ctx.config.default_git_user_name:
                warning(f"{project.name} has a different git user name: {current_name}")
                repo.config_writer().set_value("user", "name", ctx.config.default_git_user_name).release()

            config = repo.config_reader()
            if config.has_section("user"):
                current_email = config.get_value("user", "email", default=None)
                current_name = config.get_value("user", "name", default=None)
            else:
                current_email = None
                current_name = None
            config.release()
            if current_email != ctx.config.default_git_user_email:
                raise Exception(f"Git user email is not set to {ctx.config.default_git_user_email}")
            if current_name != ctx.config.default_git_user_name:
                raise Exception(f"Git user name is not set to {ctx.config.default_git_user_name}")

        # IF there are no commits, create an initial commit.
        if repo is not None:
            if not repo.head.is_valid():
                # Add .gitignore
                info(f"Initializing {project.name} with .gitignore")
                repo.git.add(".gitignore")
                repo.index.commit("Initial commit")

        # R3.2: The origin remote should be set
        if repo is not None and ctx.mode != RepoSetupMode.LOCAL:
            if not repo.remotes:
                origin_url = None
            else:
                try:
                    origin_url = repo.remote("origin").url

                    if not origin_url.startswith("git@github.com:"):
                        error(f"{project.name} has an invalid origin remote: {origin_url}")
                except ValueError:
                    origin_url = None
                    error(f"{project.name} does not have an origin remote")

            if origin_url is None:
                # Add remote
                repo.create_remote("origin", f"git@github.com:{project.github_repo}.git")

                if repo.active_branch.name == "master":
                    if allow_push:
                        # Set upstream for master branch
                        info(f"Setting upstream for master branch to origin/master for {project.name}")
                        repo.git.push("--set-upstream", "origin", "master")
                    else:
                        info(f"Skipping upstream push/config for {project.name} (allow_push=False)")

        if (project.path / "src").exists():
            pass

            # ###############################################################
            # # R2.2: Each project should have a README.md file
            # if not (project.path / 'README.md').exists():
            #     error(f"{name} does not have a README.md")

            #     if ask(f"Create README.md for {name}?"):
            #         readme = create_readme(name, Path(name), api_key=config.openai_key)
            #         write_text_file(project.path / 'README.md', readme)
            #         if ask(f"Could you review the README.md for {name}. Accept?"):
            #             pass
            #         else:
            #             os.unlink(project.path / 'README.md')

            # ###############################################################
            # # R3.1: Projects should have a clean git status
            # has_clean_git_status = False
            # if has_git:
            #     status = git_status(path)
            #     if status == []:
            #         has_clean_git_status = True

            #     else:
            #         error(f"{name} has uncommitted changes:", *status)

            #         suggested_commit_message = suggest_commit_name('\n'.join(status), api_key=config.openai_key)

            #         if ask(f"Commit changes for {name} with message: {suggested_commit_message}?"):
            #             subprocess.run(['git', 'add', '.'], cwd=path, check=True)
            #             subprocess.run(['git', 'commit', '-m', suggested_commit_message], cwd=path, check=True)
            #             has_clean_git_status = True

            #     # if os.path.exists(f'{path}/.gitignore'):
            #     #     ignore = read_ignore_file(Path(f'{path}/.gitignore'), extra_positive=['/.git'])
            #     #     # print(ignore.positive, ignore.negative)

            # R3.2: The origin remote should be set

        if (
            commit_changes
            and repo is not None
            and ctx.mode == RepoSetupMode.PROD
            and repo.active_branch.name == "master"
        ):
            commit_repo_changes(project, repo, openai_key=ctx.config.openai_key, interactive=interactive)


def _write_wabbit_legal_files(ctx: setup_common.CommonSetupContext, project: Project) -> None:
    setup_common.write_wabbit_legal_files(ctx, project)


def _write_repo_root_wabbit_legal_documents(
    ctx: setup_common.CommonSetupContext,
    repo_projects: list[GradleProject],
) -> None:
    if not repo_projects:
        return

    representative_project = repo_projects[0]
    if representative_project.ownership != OwnershipType.WABBIT:
        return

    repo_root_path = representative_project.effective_repo_root
    normalized_licenses = {canonicalize_license_key(project.license) for project in repo_projects}
    shared_license = next(iter(normalized_licenses)) if len(normalized_licenses) == 1 else None
    normalized_test_licenses = {canonicalize_license_key(project.test_license) for project in repo_projects}
    non_null_test_licenses = {item for item in normalized_test_licenses if item is not None}
    shared_test_license = next(iter(non_null_test_licenses)) if len(non_null_test_licenses) == 1 else None

    if shared_license is not None:
        repo_root_project = dataclasses.replace(
            representative_project,
            path=repo_root_path,
            license=shared_license,
            test_license=shared_test_license,
        )
        setup_common.write_wabbit_legal_files(ctx, repo_root_project)
        return

    repo_root_project = dataclasses.replace(representative_project, path=repo_root_path)
    setup_common.write_wabbit_legal_documents(ctx, repo_root_project)
    dev.io.delete_if_exists(repo_root_path / "LICENSE.md")
    dev.io.delete_if_exists(repo_root_path / "LICENSES")


def _write_banner(ctx: setup_common.CommonSetupContext, project: Project) -> None:
    setup_common.write_banner(ctx, project)


def render_python_pyproject(ctx: RepoSetupContext, project: PythonProject) -> str:
    return setup_python.render_python_pyproject(ctx, project)


def render_python_pyrightconfig(ctx: RepoSetupContext, project: PythonProject) -> str:
    return setup_python.render_python_pyrightconfig(ctx, project)


def setup_python_project(ctx: RepoSetupContext, project: PythonProject, interactive: bool = True) -> None:
    # Keep legacy monkeypatch points in tests by routing module-level callbacks.
    setup_python.write_wabbit_legal_files = _write_wabbit_legal_files
    setup_python.write_banner = _write_banner
    setup_python.setup_python_project(ctx, project, interactive=interactive)


def setup_purescript_project(ctx: RepoSetupContext, project: PurescriptProject, interactive: bool = True) -> None:
    del interactive
    dev.io.write_text_file(
        project.path / ".gitignore",
        render_template(ctx.gitignore_template) + "\n" + render_template(ctx.purescript_gitignore_template),
    )
    _write_wabbit_legal_files(ctx, project)
    _write_banner(ctx, project)


def setup_gradle_project(ctx: RepoSetupContext, project: GradleProject, interactive: bool = True) -> None:
    setup_kotlin.setup_gradle_project(ctx, project, interactive=interactive)


def _relative_project_dir(root_path: Path, project_path: Path) -> str:
    return Path(os.path.relpath(project_path.resolve(), start=root_path.resolve())).as_posix()


def _gradle_project_key(project: GradleProject) -> str:
    return project.project_id or project.effective_gradle_project_name


def _gradle_project_dependencies(config: Config, project: GradleProject) -> list[GradleProject]:
    result: list[GradleProject] = []
    seen: set[str] = set()

    def add_dependency_project(dependency: Dependency) -> None:
        target = dependency.target
        if not isinstance(target, ProjectDependencyTarget):
            return
        dependency_project = config.defined_projects[target.project]
        if not isinstance(dependency_project, GradleProject):
            return
        dependency_key = _gradle_project_key(dependency_project)
        if dependency_key in seen:
            return
        seen.add(dependency_key)
        result.append(dependency_project)

    for dependency in project.resolved_dependencies:
        add_dependency_project(dependency)
    for source_set_dependencies in project.source_set_dependencies.values():
        for dependency in source_set_dependencies:
            add_dependency_project(dependency)
    return result


def _collect_included_gradle_projects(
    config: Config,
    seed_projects: list[GradleProject],
    *,
    include_external_dependencies: bool,
) -> list[GradleProject]:
    included: list[GradleProject] = []
    seen: set[str] = set()
    queue = list(seed_projects)

    while queue:
        project = queue.pop(0)
        project_key = _gradle_project_key(project)
        if project_key in seen:
            continue
        seen.add(project_key)
        included.append(project)

        for dependency_project in _gradle_project_dependencies(config, project):
            same_repo = dependency_project.effective_repo_root == project.effective_repo_root
            if same_repo or include_external_dependencies:
                queue.append(dependency_project)

    return included


def _collect_reachable_gradle_projects(config: Config, seed_projects: list[GradleProject]) -> list[GradleProject]:
    reachable: list[GradleProject] = []
    seen: set[str] = set()
    queue = list(seed_projects)

    while queue:
        project = queue.pop(0)
        project_key = _gradle_project_key(project)
        if project_key in seen:
            continue
        seen.add(project_key)
        reachable.append(project)
        queue.extend(_gradle_project_dependencies(config, project))

    return reachable


def _local_plugin_projects(config: Config, project: GradleProject) -> list[GradleProject]:
    plugin_projects: list[GradleProject] = []
    seen: set[str] = set()
    for application in get_gradle_plugin_applications(project):
        definition = config.plugins[application.name]
        candidate = resolve_kotlin_plugin_project(config, definition)
        if candidate is None:
            continue
        candidate_key = _gradle_project_key(candidate)
        if candidate_key in seen:
            continue
        seen.add(candidate_key)
        plugin_projects.append(candidate)
    return plugin_projects


def _local_compiler_plugin_projects(config: Config, project: GradleProject) -> list[GradleProject]:
    compiler_projects: list[GradleProject] = []
    seen: set[str] = set()
    for application in get_gradle_plugin_applications(project):
        definition = config.plugins[application.name]
        candidate = resolve_kotlin_plugin_compiler_plugin_project(config, definition)
        if candidate is None:
            continue
        candidate_key = _gradle_project_key(candidate)
        if candidate_key in seen:
            continue
        seen.add(candidate_key)
        compiler_projects.append(candidate)
    return compiler_projects


def _collect_reachable_gradle_projects_for_local_mode(
    config: Config,
    seed_projects: list[GradleProject],
) -> tuple[list[GradleProject], list[GradleProject]]:
    reachable: list[GradleProject] = []
    plugin_builds: list[GradleProject] = []
    seen: set[str] = set()
    plugin_seen: set[str] = set()
    queue = list(seed_projects)

    while queue:
        project = queue.pop(0)
        project_key = _gradle_project_key(project)
        if project_key in seen:
            continue
        seen.add(project_key)
        reachable.append(project)
        queue.extend(_gradle_project_dependencies(config, project))
        for plugin_project in _local_plugin_projects(config, project):
            plugin_key = _gradle_project_key(plugin_project)
            if plugin_key not in plugin_seen:
                plugin_seen.add(plugin_key)
                plugin_builds.append(plugin_project)
            queue.append(plugin_project)
        queue.extend(_local_compiler_plugin_projects(config, project))

    return reachable, plugin_builds


def _workspace_dependency_substitutions(
    config: Config,
    included_projects: list[GradleProject],
) -> list[WorkspaceDependencySubstitution]:
    substitutions: list[WorkspaceDependencySubstitution] = []
    seen: set[str] = set()
    reachable_keys = {_gradle_project_key(project) for project in _collect_reachable_gradle_projects(config, included_projects)}

    for project in included_projects:
        project_key = _gradle_project_key(project)
        if project_key not in reachable_keys:
            continue
        module_coordinate = project.artifact_name.rsplit(":", 1)[0]
        if module_coordinate in seen:
            continue
        seen.add(module_coordinate)
        substitutions.append(
            WorkspaceDependencySubstitution(
                module_coordinate=module_coordinate,
                gradle_project_name=project.effective_gradle_project_name,
            )
        )

    return substitutions


def _included_build_project_path(project: GradleProject) -> str:
    if project.path.resolve() == project.effective_gradle_root.resolve():
        return ":"
    return f":{project.effective_gradle_project_name}"


def _local_included_builds(
    config: Config,
    *,
    root_path: Path,
    seed_projects: list[GradleProject],
) -> tuple[list[str], list[LocalIncludedBuild]]:
    reachable_projects, plugin_build_projects = _collect_reachable_gradle_projects_for_local_mode(config, seed_projects)
    local_repo_roots = {project.effective_repo_root.resolve() for project in seed_projects}
    plugin_build_keys = {_gradle_project_key(project) for project in plugin_build_projects}

    grouped_projects: dict[Path, list[GradleProject]] = {}
    for project in reachable_projects:
        if _gradle_project_key(project) in plugin_build_keys:
            continue
        project_repo_root = project.effective_repo_root.resolve()
        if project_repo_root in local_repo_roots:
            continue
        gradle_root = project.effective_gradle_root.resolve()
        grouped_projects.setdefault(gradle_root, []).append(project)

    included_builds: list[LocalIncludedBuild] = []
    for gradle_root in sorted(grouped_projects.keys()):
        substitutions: list[LocalIncludedBuildSubstitution] = []
        seen_coordinates: set[str] = set()
        for project in sorted(grouped_projects[gradle_root], key=_gradle_project_key):
            module_coordinate = project.artifact_name.rsplit(":", 1)[0]
            if module_coordinate in seen_coordinates:
                continue
            seen_coordinates.add(module_coordinate)
            substitutions.append(
                LocalIncludedBuildSubstitution(
                    module_coordinate=module_coordinate,
                    project_path=_included_build_project_path(project),
                )
            )

        if not substitutions:
            continue

        included_builds.append(
            LocalIncludedBuild(
                build_path=_relative_project_dir(root_path, gradle_root),
                substitutions=substitutions,
            )
        )

    plugin_included_builds = [
        _relative_project_dir(root_path, project.effective_gradle_root)
        for project in plugin_build_projects
        if project.effective_repo_root.resolve() not in local_repo_roots
    ]

    return plugin_included_builds, included_builds


def _write_gradle_local_overlay(
    ctx: RepoSetupContext,
    *,
    root_path: Path,
    seed_projects: list[GradleProject],
) -> None:
    overlay_path = root_path / "settings.local.gradle.kts"
    plugin_included_builds, included_builds = _local_included_builds(
        ctx.config,
        root_path=root_path,
        seed_projects=seed_projects,
    )
    if not plugin_included_builds and not included_builds:
        dev.io.delete_if_exists(overlay_path)
        return

    overlay_text = render_template(
        ctx.settings_local_template,
        plugin_included_builds=plugin_included_builds,
        included_builds=included_builds,
    )
    dev.io.write_text_file(overlay_path, stamp_managed_text(setup_kotlin.clean_gradle_build_text(overlay_text)))


def _delete_gradle_local_overlay(*, root_path: Path) -> None:
    dev.io.delete_if_exists(root_path / "settings.local.gradle.kts")


def _write_gradle_root_files(
    ctx: RepoSetupContext,
    *,
    root_path: Path,
    root_project_name: str,
    seed_projects: list[GradleProject],
    write_wrapper: bool,
    write_build: bool = True,
    include_external_dependencies: bool = False,
    write_dependency_substitutions: bool = False,
) -> None:
    root_path.mkdir(parents=True, exist_ok=True)
    included_projects = _collect_included_gradle_projects(
        ctx.config,
        seed_projects,
        include_external_dependencies=include_external_dependencies,
    )
    plugin_context = setup_kotlin.settings_plugin_context(ctx, included_projects, root_path=root_path)
    repo_definition = next(
        (
            definition
            for definition in ctx.config.defined_repos.values()
            if definition.path.resolve() == root_path.resolve()
        ),
        None,
    )
    if write_build:
        dependency_substitutions = (
            _workspace_dependency_substitutions(ctx.config, included_projects) if write_dependency_substitutions else []
        )
        inline_extra_build = setup_kotlin.read_optional_inline_gradle_build_script(root_path)
        build_text = render_template(
            ctx.build_template,
            **plugin_context,
            dependency_substitutions=dependency_substitutions,
            inline_extra_build_imports=inline_extra_build.imports,
            inline_extra_build_script=inline_extra_build.body,
        )
        dev.io.write_text_file(
            root_path / "build.gradle.kts",
            stamp_managed_text(setup_kotlin.clean_gradle_build_text(build_text)),
        )

    settings_text = render_template(
        ctx.settings_template,
        **plugin_context,
        local_plugin_included_builds=setup_kotlin.local_plugin_included_builds(
            ctx,
            root_path=root_path,
            projects=included_projects,
        ),
        root_project_name=root_project_name,
        included_projects=[
            {
                "gradle_project_name": included_project.effective_gradle_project_name,
                "project_dir": _relative_project_dir(root_path, included_project.path),
            }
            for included_project in included_projects
            if included_project.path.resolve() != root_path.resolve()
        ],
    )
    dev.io.write_text_file(
        root_path / "settings.gradle.kts",
        stamp_managed_text(setup_kotlin.clean_gradle_build_text(settings_text)),
    )

    if write_wrapper:
        dev.io.write_text_file(
            root_path / "gradle.properties",
            stamp_managed_text(
                setup_common.clean_text(
                    render_template(
                        ctx.gradle_properties_template,
                        repo_project_version=repo_definition.project_version if repo_definition is not None else None,
                        repo_default_kotlin_version=(
                            repo_definition.default_kotlin_version if repo_definition is not None else None
                        ),
                        repo_supported_kotlin_versions=(
                            repo_definition.supported_kotlin_versions if repo_definition is not None else []
                        ),
                    )
                )
            ),
        )
        dev.io.copy(ctx.repo_template / "gradle-files" / "gradlew", root_path / "gradlew")
        dev.io.copy(ctx.repo_template / "gradle-files" / "gradlew.bat", root_path / "gradlew.bat")
        setup_kotlin._mark_executable(root_path / "gradlew")
        dev.io.copy(
            ctx.repo_template / "gradle-files" / "gradle" / "wrapper" / "gradle-wrapper.jar",
            root_path / "gradle" / "wrapper" / "gradle-wrapper.jar",
        )
        dev.io.copy(
            ctx.repo_template / "gradle-files" / "gradle" / "wrapper" / "gradle-wrapper.properties",
            root_path / "gradle" / "wrapper" / "gradle-wrapper.properties",
        )


def _should_write_generated_gradle_root_build(root_path: Path) -> bool:
    build_path = root_path / "build.gradle.kts"
    if not build_path.exists():
        return True
    try:
        return build_path.read_text(encoding="utf-8").startswith(GENERATED_GRADLE_FILE_HEADER)
    except UnicodeDecodeError:
        return False


def _repo_gradle_workflow_java_version(ctx: RepoSetupContext, projects: list[GradleProject]) -> int:
    if not projects:
        return ctx.config.java_version
    return max(
        setup_kotlin.java_version_for_features(ctx.config.java_version, project.resolved_features) for project in projects
    )


def setup_gradle_repo_root(ctx: RepoSetupContext, project: GradleProject) -> None:
    repo_id = project.repo_id
    if repo_id is None or project.effective_gradle_root == Path("."):
        return

    repo_definition = ctx.config.defined_repos.get(repo_id)
    if repo_definition is None:
        raise ValueError(f"Missing repo definition for {repo_id}")

    repo_gradle_projects = [
        defined_project
        for defined_project in ctx.config.defined_projects.values()
        if isinstance(defined_project, GradleProject) and defined_project.repo_id == repo_id
    ]
    if not repo_gradle_projects:
        return

    _write_gradle_root_files(
        ctx,
        root_path=repo_definition.path,
        root_project_name=repo_definition.gradle_root_project_name or repo_id,
        seed_projects=repo_gradle_projects,
        write_wrapper=True,
        write_build=_should_write_generated_gradle_root_build(repo_definition.path),
        include_external_dependencies=False,
        write_dependency_substitutions=False,
    )
    _write_repo_root_wabbit_legal_documents(ctx, repo_gradle_projects)
    docs_project: GradleProject | None = None
    if repo_definition.docs_project_id is not None:
        defined_docs_project = ctx.config.defined_projects.get(repo_definition.docs_project_id)
        if isinstance(defined_docs_project, GradleProject):
            docs_project = defined_docs_project
    setup_kotlin._write_gradle_repo_root_workflows(
        ctx,
        root_path=repo_definition.path,
        repo_github_repo=repo_definition.github_repo,
        projects=repo_gradle_projects,
        docs_project=docs_project,
        java_version=_repo_gradle_workflow_java_version(ctx, repo_gradle_projects),
    )


USED_COMMIT_MESSAGES: dict[str, str] = {}


def commit_repo_changes(
    project: Project,
    repo: Repo,
    openai_key: str | None = None,
    interactive: bool = True,
    add_files: bool = True,
) -> None:
    """
    Example function that:
      1) Gathers the repo changes (untracked, staged, unstaged).
      2) Prints warnings/errors.
      3) Optionally stages untracked/unstaged files based on user prompts.
      4) Displays a unified diff for each file that changed (HEAD -> WORKING).
      5) Suggests a commit message.
      6) Optionally commits.
    """

    if project.quarantine:
        # Skip commit if project is in quarantine
        error(f"Skipping commit for {project.name} (quarantine mode)")
        return

    try:
        diffs: list[FileDiff] = compute_repo_diffs(repo)
    except Exception as ex:
        error(f"Cannot proceed: {ex}")
        return

    if add_files:
        # -------------------------------------------------------------------------
        # Prompt about untracked files
        # -------------------------------------------------------------------------
        untracked_paths = [d.new_path for d in diffs if d.untracked]
        if untracked_paths:
            error(f"{project.name} has untracked files:", *untracked_paths)
            if not interactive or ask(f"Add untracked files for {project.name}?"):
                repo.git.add(*untracked_paths)
            else:
                raise Exception("Untracked files exist")

        # -------------------------------------------------------------------------
        # Prompt about unstaged changes
        # -------------------------------------------------------------------------
        unstaged_paths = [d.new_path for d in diffs if d.unstaged and not d.untracked]
        if unstaged_paths:
            error(f"{project.name} has unstaged changes:")
            for path in unstaged_paths:
                print(f"  {path}")
            if not interactive or ask(f"Add unstaged changes for {project.name}?"):
                repo.git.add(*unstaged_paths)
            else:
                raise Exception("Unstaged changes exist")

    # Re-gather changes after optional staging and use this as the single source of truth.
    final_diffs: list[FileDiff] = compute_repo_diffs(repo, include_untracked=True)
    has_changes = any(diff_item.change_type != ChangeType.UNCHANGED for diff_item in final_diffs)

    if has_changes:
        warning(f"{project.name}: Changes on master")

        # ---------------------------------------------------------------------
        # Build a user-readable diff summary for HEAD->WORKING
        # using the FileDiff objects from gather_changes again (or we can re-run).
        # We'll do a single pass and write all info into buf.
        # ---------------------------------------------------------------------
        buf = io.StringIO()
        for diff_item in final_diffs:
            # Skip unchanged files (shouldn't normally be returned, but check anyway)
            if diff_item.change_type == ChangeType.UNCHANGED:
                continue

            # --- File Path ---
            path_str = ""
            if diff_item.change_type == ChangeType.ADDED or diff_item.change_type == ChangeType.UNTRACKED:
                path_str = f"File: {diff_item.new_path} (Added)"
            elif diff_item.change_type == ChangeType.DELETED:
                path_str = f"File: {diff_item.old_path} (Deleted)"
            elif diff_item.change_type == ChangeType.RENAMED:
                path_str = f"File: {diff_item.old_path} => {diff_item.new_path} (Renamed)"
            else:  # MODIFIED, MODE_CHANGED, TYPE_CHANGED
                path_str = f"File: {diff_item.path}"  # Use the primary path attribute

            print(path_str, file=buf)

            # --- Status & Flags ---
            status_str = diff_item.change_type.name
            flags: list[str] = []
            if diff_item.staged:
                flags.append("Staged")
            if diff_item.unstaged:
                flags.append("Unstaged")
            if diff_item.untracked:
                flags.append("Untracked")
            if diff_item.partial_staging_suspected:
                flags.append("Partial")

            print(f"  Status: {status_str} [{', '.join(flags)}]", file=buf)

            # --- Mode Change ---
            if (
                diff_item.old_mode is not None
                and diff_item.new_mode is not None
                and diff_item.old_mode != diff_item.new_mode
            ):
                # Only print mode change if it's the *only* change, otherwise it's implied in MODIFIED
                if diff_item.change_type == ChangeType.MODE_CHANGED:
                    print(
                        f"  Mode changed: {oct(diff_item.old_mode)} -> {oct(diff_item.new_mode)}",
                        file=buf,
                    )
                else:
                    # Optionally add a note if mode changed alongside content
                    print(
                        f"  Mode also changed: {oct(diff_item.old_mode)} -> {oct(diff_item.new_mode)}",
                        file=buf,
                    )

            # --- Content Diff (Text/Binary) ---
            is_text_change = diff_item.old_type in (
                FileType.TEXT,
                FileType.EMPTY,
            ) and diff_item.new_type in (FileType.TEXT, FileType.EMPTY)

            if diff_item.binary_different:
                print("  Binary difference detected", file=buf)
            elif is_text_change and diff_item.unified_diff:
                # Show the diff for text changes
                print("  Diff:", file=buf)
                # Simple diff tagging for clarity
                print(f'<diff path="{diff_item.path}">', file=buf)
                # Indent diff lines for readability
                for line in diff_item.unified_diff.splitlines():
                    print(f"    {line}", file=buf)
                print("</diff>", file=buf)
            elif (
                not diff_item.binary_different
                and not diff_item.unified_diff
                and diff_item.change_type not in (ChangeType.ADDED, ChangeType.DELETED, ChangeType.MODE_CHANGED)
            ):
                # If no binary diff and no text diff, but status is MODIFIED/RENAMED etc.
                # it might be a subtle change (e.g. whitespace only, if diff generation skipped it)
                print(
                    "  Note: Content difference detected, but no textual diff generated (check whitespace/type).",
                    file=buf,
                )
            elif diff_item.change_type == ChangeType.ADDED:
                if diff_item.new_type == FileType.BINARY:
                    print("  New binary file", file=buf)
                elif diff_item.new_type == FileType.EMPTY:
                    print("  New empty file", file=buf)
                elif diff_item.unified_diff:  # New text file with content
                    print("  Diff (New File):", file=buf)
                    print(f'<diff path="{diff_item.path}">', file=buf)
                    for line in diff_item.unified_diff.splitlines():
                        print(f"    {line}", file=buf)
                    print("</diff>", file=buf)
                else:  # New text file, but no diff generated (shouldn't happen often)
                    print("  New text file (no diff content found)", file=buf)
            elif diff_item.change_type == ChangeType.DELETED:
                if diff_item.old_type == FileType.BINARY:
                    print("  Deleted binary file", file=buf)
                else:
                    print("  Deleted text/empty file", file=buf)
            # No need for explicit UNCHANGED check here as we skipped it earlier

            print(file=buf)  # blank line after each file

        # --- Process the assembled diff text ---
        final_diff_text = buf.getvalue()
        buf.close()

        # Assuming tiktoken is installed and available
        try:
            tiktoken = __import__("tiktoken")
            enc = tiktoken.encoding_for_model("gpt-3.5-turbo")
            num_tokens = len(enc.encode(final_diff_text))
            print(f"Number of tokens in diff text: {num_tokens}")
        except ImportError:
            print("Warning: tiktoken not installed. Cannot calculate token count.")
            num_tokens = len(final_diff_text) // 4  # Rough estimate
            print(f"Estimated token count: ~{num_tokens}")

        import hashlib

        h = hashlib.md5(final_diff_text.encode("utf-8")).hexdigest()
        if h in USED_COMMIT_MESSAGES:
            commit_name = USED_COMMIT_MESSAGES[h]
        else:
            if num_tokens > 100000:  # Example token limit
                # Spawn editor
                editor = os.environ.get("EDITOR", "vim")  # Use vim as fallback
                # Use a more robust temp file location if possible, or ensure .git dir exists
                commit_file_path = Path(repo.working_dir) / ".git" / "COMMIT_EDITMSG"
                commit_file_path.parent.mkdir(parents=True, exist_ok=True)  # Ensure .git dir exists

                # Create a temporary commit message file
                commit_file_text = f"\n\n# Commit changes for {project.name}\n# Changes detected:\n"
                # Add a summary of changed files to the commit message template
                for diff_item in final_diffs:
                    if diff_item.change_type != ChangeType.UNCHANGED:
                        commit_file_text += f"#  {diff_item.change_type.name}: {diff_item.path}\n"

                try:
                    with open(commit_file_path, "w", encoding="utf-8") as f:
                        f.write(commit_file_text)

                    # Use full path for editor command
                    status = os.system(f'{editor} "{str(commit_file_path)}"')  # Quote path
                    if status != 0:
                        warning(f"Editor '{editor}' exited with status {status}. Commit message might not be saved.")

                    with open(commit_file_path, encoding="utf-8") as f:
                        # Read the commit message from the file and strip it
                        # of leading/trailing whitespace and comments
                        commit_name = f.read().strip()
                        # Remove comment lines more carefully
                        commit_lines = [line for line in commit_name.splitlines() if not line.strip().startswith("#")]
                        commit_name = "\n".join(commit_lines).strip()

                    if not commit_name:
                        warning("Commit message is empty after editing. Aborting commit.")
                        # Handle empty commit message case (e.g., raise error, return None)
                        commit_name = None  # Or raise an exception
                    else:
                        print(f"Using commit message from editor:\n---\n{commit_name}\n---")

                except Exception as e:
                    warning(f"Error handling commit message editing: {e}")
                    commit_name = f"Error processing commit message for {project.name}"  # Fallback

                finally:
                    # Clean up commit message file if it still exists
                    if commit_file_path.exists():
                        try:
                            commit_file_path.unlink()
                        except OSError as e:
                            warning(f"Could not remove temporary commit file {commit_file_path}: {e}")

            else:
                print("--- Generated Diff Summary ---")
                print(final_diff_text)
                print("--- End Diff Summary ---")
                # Suggest a commit message using the assembled patch content
                # Ensure suggest_commit_name handles potential errors
                api_key = openai_key if openai_key is not None else ""
                try:
                    repo_working_tree = repo.working_tree_dir
                except AttributeError:
                    repo_working_tree = None
                repo_path = str(repo_working_tree) if repo_working_tree is not None else None
                commit_name = suggest_commit_name(
                    final_diff_text,
                    api_key=api_key,
                    repo_path=repo_path,
                )
                print(f"Suggested commit message: {commit_name}")

        if commit_name is not None:
            commit_name = ensure_semver_impact_line(commit_name)
        else:
            commit_name = ensure_semver_impact_line(f"Update {project.name}")

        # Optionally commit if user agrees

        if interactive:
            while True:
                info(f"Commit message: {commit_name}")
                r = ask(f"Commit changes on master for {project.name}?", result_type="yne")
                if r == "y":
                    USED_COMMIT_MESSAGES[h] = commit_name
                    repo.git.add(all=True)
                    repo.index.commit(commit_name)
                    break
                elif r == "e":
                    # Spawn editor
                    editor = os.environ.get("EDITOR", "vim")
                    commit_file = Path(repo.working_dir) / ".git/COMMIT_EDITMSG"
                    with open(commit_file, "w") as f:
                        f.write(commit_name)
                    os.system(f"{editor} {repo.working_dir}/.git/COMMIT_EDITMSG")
                    with open(commit_file) as f:
                        commit_name = f.read().strip()
                    if commit_name:
                        commit_name = ensure_semver_impact_line(commit_name)
                else:
                    raise Exception("Changes on master")
        else:
            repo.git.add(all=True)
            repo.index.commit(commit_name)


def create_repo_setup_context(config: Config, mode: RepoSetupMode) -> RepoSetupContext:
    from github import Github
    from github.GithubException import GithubException
    from requests.exceptions import RequestException

    all_repos = []
    known_repo_names: list[str] = []
    known_github_repos: dict[str, RepoInfo] = {}
    is_github_api_available = False

    if not config.github_token:
        warning("GitHub token not set; proceeding without GitHub API.")
    else:
        try:
            gh = Github(login_or_token=config.github_token, retry=0)

            # list(wabbit_corp_org.get_repos()) + list(corsaircraft_org.get_repos()) +
            # list(sir_wabbit_org.get_repos()) + \
            all_repos = list(gh.get_user().get_repos())
            known_repo_names = [r.full_name for r in all_repos]
            known_github_repos = {
                r.full_name: RepoInfo(
                    organization=r.owner.login,
                    name=r.name,
                    is_private=r.private,
                )
                for r in all_repos
            }

            for repo in all_repos:
                print(f"Repo: {repo.name} ({repo.full_name}) - {repo.private} - {repo.clone_url}")

            is_github_api_available = True
        except TimeoutError as ex:
            warning(f"GitHub API timed out; proceeding without API: {ex}")
        except (GithubException, RequestException, OSError) as ex:
            warning(f"GitHub API unavailable; proceeding without API: {ex}")
        except ValueError as ex:
            warning(f"GitHub API error; proceeding without API: {ex}")

    if not is_github_api_available:
        all_repos = []
        known_repo_names = []
        known_github_repos = {}

    repo_template = Path("data-repo-template")

    return RepoSetupContext(
        config=config,
        known_repo_names=known_repo_names,
        known_github_repos=known_github_repos,
        repo_template=repo_template,
        is_github_api_available=is_github_api_available,
        licenses=load_license_texts(repo_template / "legal" / "licenses"),
        gitignore_template=dev.io.read_template(repo_template / "gitignore.jinja2"),
        cla=dev.io.read_template(repo_template / "legal" / "cla" / "v1.0.0" / "CLA.md", strict=True),
        cla_explanations=dev.io.read_template(
            repo_template / "legal" / "cla" / "v1.0.0" / "CLA_EXPLANATIONS.md",
            strict=True,
        ),
        coc=dev.io.read_template(
            repo_template / "legal" / "code-of-conduct" / "v1.0.0" / "CODE_OF_CONDUCT.md",
            strict=True,
        ),
        contributor_privacy_policy=dev.io.read_template(
            repo_template / "legal" / "contributor-privacy" / "v1.0.0" / "CONTRIBUTOR_PRIVACY.md",
            strict=True,
        ),
        gradle_gitignore_template=dev.io.read_template(repo_template / "gradle-files" / "gitignore.jinja2"),
        settings_template=dev.io.read_template(repo_template / "gradle-files" / "settings.gradle.kts.jinja2"),
        settings_local_template=dev.io.read_template(
            repo_template / "gradle-files" / "settings.local.gradle.kts.jinja2"
        ),
        subproject_settings_template=dev.io.read_template(
            repo_template / "gradle-files" / "subproject-settings.gradle.kts.jinja2"
        ),
        build_template=dev.io.read_template(repo_template / "gradle-files" / "build.gradle.kts.jinja2"),
        subproject_build_template=dev.io.read_template(
            repo_template / "gradle-files" / "subproject-build.gradle.kts.jinja2"
        ),
        subproject_build_kmp_template=dev.io.read_template(
            repo_template / "gradle-files" / "subproject-build-kmp.gradle.kts.jinja2"
        ),
        gradle_properties_template=dev.io.read_template(repo_template / "gradle-files" / "gradle.properties.jinja2"),
        python_gitignore_template=dev.io.read_template(repo_template / "python-files" / "gitignore.jinja2"),
        purescript_gitignore_template=dev.io.read_template(repo_template / "purescript-files" / "gitignore.jinja2"),
        python_pyproject_template=dev.io.read_template(repo_template / "python-files" / "pyproject.toml.jinja2"),
        python_pyrightconfig_template=dev.io.read_template(
            repo_template / "python-files" / "pyrightconfig.json.jinja2"
        ),
        python_mkdocs_template=dev.io.read_template(repo_template / "python-files" / "mkdocs.yml.jinja2"),
        python_docs_index_template=dev.io.read_template(repo_template / "python-files" / "docs" / "index.md.jinja2"),
        python_docs_installation_template=dev.io.read_template(
            repo_template / "python-files" / "docs" / "installation.md.jinja2"
        ),
        python_docs_development_template=dev.io.read_template(
            repo_template / "python-files" / "docs" / "development.md.jinja2"
        ),
        python_contributing_template=dev.io.read_template(repo_template / "python-files" / "CONTRIBUTING.md.jinja2"),
        python_docs_quality_workflow_template=dev.io.read_template(
            repo_template / "python-files" / ".github" / "workflows" / "docs-quality.yml.jinja2"
        ),
        python_docs_deploy_workflow_template=dev.io.read_template(
            repo_template / "python-files" / ".github" / "workflows" / "docs-deploy.yml.jinja2"
        ),
        gradle_release_publish_workflow_template=dev.io.read_template(
            repo_template / "gradle-files" / ".github" / "workflows" / "release-publish.yml.jinja2"
        ),
        gradle_snapshot_publish_workflow_template=dev.io.read_template(
            repo_template / "gradle-files" / ".github" / "workflows" / "snapshot-publish.yml.jinja2"
        ),
        gradle_compiler_plugin_release_publish_workflow_template=dev.io.read_template(
            repo_template / "gradle-files" / ".github" / "workflows" / "compiler-plugin-release-publish.yml.jinja2"
        ),
        gradle_compiler_plugin_snapshot_publish_workflow_template=dev.io.read_template(
            repo_template / "gradle-files" / ".github" / "workflows" / "compiler-plugin-snapshot-publish.yml.jinja2"
        ),
        gradle_docs_quality_workflow_template=dev.io.read_template(
            repo_template / "gradle-files" / ".github" / "workflows" / "docs-quality.yml.jinja2"
        ),
        gradle_docs_deploy_workflow_template=dev.io.read_template(
            repo_template / "gradle-files" / ".github" / "workflows" / "docs-deploy.yml.jinja2"
        ),
        python_codespell_ignore_words_template=dev.io.read_template(
            repo_template / "python-files" / ".codespell-ignore-words.txt.jinja2"
        ),
        python_build_executable_template=dev.io.read_template(
            repo_template / "python-files" / "scripts" / "build_executable.py.jinja2"
        ),
        mode=mode,
    )


def setup(
    mode: RepoSetupMode,
    *,
    interactive: bool = True,
    project: str | None = None,
    projects: list[str] | None = None,
    json_output: bool = False,
) -> int:
    selected_projects_input = projects if projects is not None else ([project] if project is not None else None)
    if selected_projects_input == []:
        selected_projects_input = None

    payload: dict[str, object] = {
        "mode": mode.value,
        "requestedTargets": list(selected_projects_input or []),
        "selectedProjectIds": [],
        "projects": [],
        "workspaceGradleRootWritten": False,
        "repoGradleRootsWritten": [],
        "localOverlayRootsWritten": [],
        "localOverlayRootsRemoved": [],
        "unexpectedDirectories": [],
    }

    def project_payload(project_item: Project | object) -> dict[str, object]:
        path = getattr(project_item, "path", None)
        project_id = getattr(project_item, "project_id", None)
        return {
            "projectId": project_id or getattr(project_item, "name", str(path)),
            "path": str(path.resolve()) if isinstance(path, Path) else None,
            "repoId": getattr(project_item, "repo_id", None),
            "type": type(project_item).__name__.removesuffix("Project").lower(),
        }

    def run() -> int:
        config = load_config()
        ctx = create_repo_setup_context(config, mode)

        if selected_projects_input is None:
            selected_project_names = list(config.defined_projects.keys())
        else:
            from dev.repo_resolution import resolve_project_ids

            try:
                resolved_project_ids = resolve_project_ids(config, selected_projects_input)
            except ValueError as ex:
                payload["error"] = str(ex)
                error(str(ex))
                return 1
            selected_project_names = toposort_projects(config.defined_projects, target_project=resolved_project_ids)

        payload["selectedProjectIds"] = list(selected_project_names)
        selected_projects = [config.defined_projects[name] for name in selected_project_names]
        payload["projects"] = [project_payload(project_item) for project_item in selected_projects]

        if selected_projects_input is None:
            info(f"Setting up projects in {mode.value} mode")
        else:
            if len(selected_projects_input) == 1:
                target_label = selected_projects_input[0]
            else:
                target_label = ", ".join(selected_projects_input)
            info(f"Setting up {target_label} and its dependencies in {mode.value} mode")

        gradle_projects = [project_item for project_item in selected_projects if isinstance(project_item, GradleProject)]
        if gradle_projects:
            if selected_projects_input is None:
                workspace_seed_projects = gradle_projects
                workspace_root_name = config.default_maven_project_group or "workspace"
                payload["workspaceGradleRootWritten"] = True
                _write_gradle_root_files(
                    ctx,
                    root_path=Path("."),
                    root_project_name=workspace_root_name,
                    seed_projects=workspace_seed_projects,
                    write_wrapper=False,
                    write_build=True,
                    include_external_dependencies=mode == RepoSetupMode.LOCAL,
                    write_dependency_substitutions=mode == RepoSetupMode.LOCAL,
                )

            repo_ids_to_write = {
                project_item.repo_id
                for project_item in gradle_projects
                if project_item.repo_id is not None and project_item.effective_gradle_root != Path(".")
            }
            repo_gradle_roots_written: list[str] = []
            for repo_id in sorted(repo_ids_to_write):
                representative_project = next(
                    (
                        defined_project
                        for defined_project in config.defined_projects.values()
                        if isinstance(defined_project, GradleProject) and defined_project.repo_id == repo_id
                    ),
                    None,
                )
                if representative_project is None:
                    continue
                repo_gradle_roots_written.append(str(representative_project.effective_gradle_root.resolve()))
                setup_gradle_repo_root(ctx, representative_project)
            payload["repoGradleRootsWritten"] = repo_gradle_roots_written

        for setup_project_item in selected_projects:
            setup_project(
                ctx,
                setup_project_item,
                interactive=interactive,
                commit_changes=False,
                allow_push=False,
            )

        if mode == RepoSetupMode.LOCAL:
            local_overlay_roots_written: list[str] = []
            repo_ids_to_overlay = {
                project_item.repo_id
                for project_item in gradle_projects
                if project_item.repo_id is not None and project_item.effective_gradle_root != Path(".")
            }
            for repo_id in sorted(repo_ids_to_overlay):
                repo_definition = config.defined_repos.get(repo_id)
                if repo_definition is None:
                    continue
                repo_gradle_projects = [
                    defined_project
                    for defined_project in config.defined_projects.values()
                    if isinstance(defined_project, GradleProject) and defined_project.repo_id == repo_id
                ]
                if not repo_gradle_projects:
                    continue
                local_overlay_roots_written.append(str(repo_definition.path.resolve()))
                _write_gradle_local_overlay(
                    ctx,
                    root_path=repo_definition.path,
                    seed_projects=repo_gradle_projects,
                )

            standalone_gradle_projects = [
                project_item
                for project_item in selected_projects
                if isinstance(project_item, GradleProject) and project_item.effective_gradle_root == project_item.path
            ]
            for standalone_project in standalone_gradle_projects:
                local_overlay_roots_written.append(str(standalone_project.path.resolve()))
                _write_gradle_local_overlay(
                    ctx,
                    root_path=standalone_project.path,
                    seed_projects=[standalone_project],
                )
            payload["localOverlayRootsWritten"] = local_overlay_roots_written
        else:
            overlay_roots: set[Path] = set()
            if selected_projects_input is None and gradle_projects:
                overlay_roots.add(Path("."))
            overlay_roots.update(project_item.effective_gradle_root for project_item in gradle_projects)
            payload["localOverlayRootsRemoved"] = [str(overlay_root.resolve()) for overlay_root in sorted(overlay_roots)]
            for overlay_root in sorted(overlay_roots):
                _delete_gradle_local_overlay(root_path=overlay_root)

        if selected_projects_input is None:
            project_dirs: list[str] = []
            for project_item in selected_projects:
                relative_parts = project_item.path.parts
                if relative_parts and relative_parts[0] == ".":
                    relative_parts = relative_parts[1:]
                if relative_parts:
                    project_dirs.append(relative_parts[0])
            ignored_dirs = [
                "build",
                ".gradle",
                "gradle",
                ".idea",
                ".git",
                ".idea",
                ".vscode",
                ".venv",
                ".llm",
                ".kotlin",
                ".ipynb_checkpoints",
            ]

            def is_ignored_dir(dir: Path) -> bool:
                return dir.name in ignored_dirs or dir.name.startswith("tmp.")

            unexpected_directories: list[str] = []
            for dir in sorted(Path(".").iterdir()):
                if dir.is_dir() and dir.name not in project_dirs and not is_ignored_dir(dir):
                    unexpected_directories.append(str(dir.resolve()))
                    warning(f"Found unexpected directory: {dir}")
            payload["unexpectedDirectories"] = unexpected_directories

        payload["summary"] = {
            "selectedProjectCount": len(selected_project_names),
            "gradleProjectCount": len(gradle_projects),
        }
        info("All projects set up complete.")
        return 0

    output_context = redirect_stdout(sys.stderr) if json_output else nullcontext()
    with output_context:
        exit_code = run()

    if json_output:
        print(json.dumps(payload, indent=2))
    return exit_code


__all__ = [
    "RepoSetupMode",
    "RepoSetupContext",
    "create_repo_setup_context",
    "setup_gradle_repo_root",
    "setup",
]
